export * from './AriesFrameworkError'
export * from './RecordNotFoundError'
export * from './RecordDuplicateError'
export * from './IndySdkError'
//export * from './ClassValidationError'
//export * from './MessageSendingError'
export { WalletDuplicateError } from './WalletDuplicateError'
export { WalletNotFoundError } from './WalletNotFoundError'
export { WalletInvalidKeyError } from './WalletInvalidKeyError'
export { WalletError } from './WalletError'
